# Generated by Django 5.2.3 on 2025-06-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_evento",
                    models.CharField(
                        help_text="ID único del evento proporcionado por USGS",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "magnitud",
                    models.DecimalField(
                        decimal_places=2, help_text="Magnitud del sismo", max_digits=4
                    ),
                ),
                (
                    "lugar",
                    models.CharField(help_text="Ubicación del sismo", max_length=255),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(help_text="Fecha y hora del sismo"),
                ),
                ("latitud", models.FloatField(help_text="Latitud del epicentro")),
                ("longitud", models.FloatField(help_text="Longitud del epicentro")),
                (
                    "profundidad",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Profundidad del sismo en km",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
