# Generated by Django 5.0.6 on 2024-06-14 07:00

from django.db import migrations

# Importamos el servicio correspondiente a los sismos
from sismologia.services import obtener_y_guardar_sismos

def cargar_datos_sismos(apps, schema_editor):
    """
    Esta función llama al servicio que obtiene y guarda los sismos desde el USGS.
    """
    print("\nEjecutando migración de datos para cargar sismos iniciales...")
    obtener_y_guardar_sismos()
    print("Carga de datos iniciales de sismos completada.")


class Migration(migrations.Migration):

    dependencies = [
        ('sismologia', '0001_initial'),
    ]

    operations = [
        # Ejecutamos la función que carga los datos de los sismos
        migrations.RunPython(cargar_datos_sismos),
    ]
