# Generated by Django 5.2.3 on 2025-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incendio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=100)),
                ("comuna", models.CharField(max_length=100)),
                ("provincia", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                (
                    "superficie_total",
                    models.FloatField(
                        default=0.0, help_text="Superficie total afectada en hectáreas"
                    ),
                ),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Incendio Forestal",
                "verbose_name_plural": "Incendios Forestales",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
