# Generated by Django 5.0.6 on 2024-06-14 06:15

from django.db import migrations

# NUEVO: Importamos nuestro servicio que ya sabe cómo buscar y guardar incendios
from incendios.services import obtener_y_guardar_incendios

# NUEVO: Creamos una función que Django pueda ejecutar
def cargar_datos_iniciales(apps, schema_editor):
    """
    Esta función se ejecuta durante la migración y llama a nuestro servicio
    para poblar la base de datos de incendios.
    """
    print("\nEjecutando migración de datos para cargar incendios iniciales...")
    obtener_y_guardar_incendios()
    print("Carga de datos iniciales de incendios completada.")


class Migration(migrations.Migration):

    dependencies = [
        ('incendios', '0001_initial'), # Depende de que la tabla de incendios ya esté creada
    ]

    operations = [
        # NUEVO: Esta es la operación que ejecuta nuestra función
        migrations.RunPython(cargar_datos_iniciales),
    ]